seed: 42
dataset: officehome
data_dir: ./dataset/data_folder/officehome
model_name: module_small_patch16_224
moe_layers: FFFFFFFFFFSS
num_experts: 8
gate_k: 2
expert_depth: 2
expert_hidden_ratio: 2
unlearn_algo: finetune
unlearn_setting: domain
forget_domains:
- 1
epochs: 20
batch_size: 128
lr: 0.0001
weight_decay: 0.0
fa_threshold: 0.1
pretrained_model_path: runs/_base_models/officehome_M8_k2_seed42/checkpoints/learn_best.pt
output_dir: runs/main_table_officehome_seed42_c10d1/ft_officehome_domain/checkpoints
study_name: Fine-Tuning__OfficeHome__domain__ft_officehome_domain__seed42_d1
wandb_group: MainTable_OfficeHome_seed42_c10d1
wandb_tags:
- main_table
- OfficeHome
- domain
- Fine-Tuning
- seed42
- d1
baseline_name: Fine-Tuning
scenario: domain
config_name: ft_officehome_domain
config_path: config/main_table_officehome_seed42/ft_officehome_domain.yaml
learning_rate: 0.0001
wandb_mode: online
