seed: 42
dataset: officehome
data_dir: ./dataset/data_folder/officehome
model_name: module_small_patch16_224
moe_layers: FFFFFFFFFFSS
num_experts: 8
gate_k: 2
expert_depth: 2
expert_hidden_ratio: 2
unlearn_algo: l1_sparse
unlearn_setting: class
forget_classes:
- 0
epochs: 20
batch_size: 128
lr: 0.0001
weight_decay: 0.0
fa_threshold: 0.1
alpha: 0.1
pretrained_model_path: runs/_base_models/officehome_M8_k2_seed42/checkpoints/learn_best.pt
output_dir: runs/main_table_officehome_seed42/l1_sparse_officehome_class/checkpoints
study_name: l1-sparse__OfficeHome__class__l1_sparse_officehome_class__seed42
wandb_group: MainTable_OfficeHome_seed42
wandb_tags:
- main_table
- OfficeHome
- class
- l1-sparse
- seed42
baseline_name: l1-sparse
scenario: class
config_name: l1_sparse_officehome_class
config_path: config/main_table_officehome_seed42/l1_sparse_officehome_class.yaml
learning_rate: 0.0001
wandb_mode: online
