name: officehome_ssd_domain_baseline_d1
output_root: runs
learn:
  seed: 42
  dataset: officehome
  data_dir: ./dataset/data_folder/officehome
  unlearn_setting: random
  forget_ratio: 0.1
  model_name: module_small_patch16_224
  pretrained: true
  moe_layers: FFFFFFFFFFSS
  num_experts: 8
  gate_k: 2
  expert_depth: 2
  expert_hidden_ratio: 2
  epochs: 100
  batch_size: 128
  lr: 0.0005
  weight_decay: 0.05
  lambda_sparse: 0.5
  lambda_balance: 0.5
  lambda_div: 0.5
  ema_alpha: 0.9
  wandb_mode: online
unlearn:
  unlearn_algo: ssd
  unlearn_setting: domain
  forget_domains:
  - 1
  study_name: SSD__OfficeHome__domain__officehome_ssd_domain__seed42_d1
  epochs: 1
  batch_size: 128
  lr: 0.0001
  weight_decay: 0.0
  fa_threshold: 0.8
  selection_weighting: 10.0
  dampening_constant: 1.0
  ssd_lower_bound: 1.0
  ssd_exponent: 1.0
  wandb_mode: online
  wandb_group: MainTable_OfficeHome_seed42_c10d1
  wandb_tags:
  - main_table
  - OfficeHome
  - domain
  - SSD
  - seed42
  - d1
  baseline_name: SSD
  dataset: officehome
  dataset_name: OfficeHome
  scenario: domain
  config_name: officehome_ssd_domain
  config_path: config/main_table_officehome_seed42/officehome_ssd_domain.yaml
  learning_rate: 0.0001
