seed: 42
dataset: pacs
data_dir: ./dataset/data_folder/pacs
model_name: module_small_patch16_224
moe_layers: FFFFFFFFFFSS
num_experts: 8
gate_k: 2
expert_depth: 2
expert_hidden_ratio: 2
unlearn_algo: module
unlearn_setting: class
forget_classes:
- 0
epochs: 20
batch_size: 128
lr: 0.0001
weight_decay: 0.0
fa_threshold: 0.1
k_u: 4
selection_option: diff
update_scope: selected_experts_and_head
alpha: 1.0
beta: 1.0
gamma: 1.0
eta: 1.0
wandb_mode: online
wandb_group: LossWeight_PACS
baseline_name: ModULE
scenario: class
lambda_sparse: 1.0
lambda_balance: 1.0
lambda_div: 0.1
study_name: lossw_unl_class_sp1_bal1_div0p1
wandb_tags:
- loss_weight
- PACS
- class
- sp1_bal1_div0p1
pretrained_model_path: runs/_base_models/lossw_sp1_bal1_div0p1/checkpoints/base_sp1_bal1_div0p1_best.pt
output_dir: runs/lossw/sp1_bal1_div0p1/checkpoints
