seed: 42
dataset: pacs
data_dir: ./dataset/data_folder/pacs
model_name: module_small_patch16_224
pretrained: true
moe_layers: FFFFFFFFFFSS
num_experts: 8
gate_k: 2
expert_depth: 2
expert_hidden_ratio: 2
epochs: 100
batch_size: 128
lr: 0.0005
weight_decay: 0.05
lambda_sparse: 0.5
lambda_balance: 0.5
lambda_div: 0.5
ema_alpha: 0.9
unlearn_setting: class
forget_classes:
- 0
output_root: runs/main_table_pacs_seed42/retrain_pacs_class
k_u: 4
baseline_name: Retraining
dataset_name: PACS
scenario: class
config_name: retrain_pacs_class
config_path: config/main_table_pacs_seed42/retrain_pacs_class.yaml
learning_rate: 0.0005
git_sha: de4238adaca520fc69b1be448f369e20f6783dba
wandb_group: MainTable_PACS_seed42
wandb_tags:
- main_table
- PACS
- class
- Retraining
- seed42
learn_eval_every: 1
