seed: 42
dataset: cifar100
data_dir: ./dataset/data_folder/cifar100
model_name: module_small_patch16_224
moe_layers: FFFFFFFFFFSS
num_experts: 8
gate_k: 2
expert_depth: 2
expert_hidden_ratio: 2
unlearn_algo: boundary_shrink
unlearn_setting: class
forget_classes:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
epochs: 20
batch_size: 128
lr: 0.0001
weight_decay: 0.0
fa_threshold: 0.1
epsilon: 0.1
pretrained_model_path: runs/_base_models/cifar100_M8_k2_seed42/checkpoints/learn_best.pt
output_dir: runs/main_table_cifar100_seed42_c10/boundary_shrink_cifar100_class/checkpoints
study_name: BoundaryShrink__CIFAR100__class__boundary_shrink_cifar100_class__seed42_c10
wandb_group: MainTable_CIFAR100_seed42_c10
wandb_tags:
- main_table
- CIFAR100
- class
- BoundaryShrink
- seed42
- c10
baseline_name: Boundary Shrink
scenario: class
config_name: boundary_shrink_cifar100_class
config_path: config/main_table_cifar100_seed42/boundary_shrink_cifar100_class.yaml
learning_rate: 0.0001
wandb_mode: online
