name: cifar100_ssd_class_baseline_c10
output_root: runs
learn:
  seed: 42
  dataset: cifar100
  data_dir: ./dataset/data_folder/cifar100
  unlearn_setting: random
  forget_ratio: 0.1
  model_name: module_small_patch16_224
  pretrained: true
  moe_layers: FFFFFFFFFFSS
  num_experts: 8
  gate_k: 2
  expert_depth: 2
  expert_hidden_ratio: 2
  epochs: 100
  batch_size: 128
  lr: 0.0005
  weight_decay: 0.05
  lambda_sparse: 0.5
  lambda_balance: 0.5
  lambda_div: 0.5
  ema_alpha: 0.9
  wandb_mode: online
unlearn:
  unlearn_algo: ssd
  unlearn_setting: class
  forget_classes:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  study_name: SSD__CIFAR100__class__cifar100_ssd_class__seed42_c10
  epochs: 1
  batch_size: 128
  lr: 0.0001
  weight_decay: 0.0
  fa_threshold: 0.8
  selection_weighting: 10.0
  dampening_constant: 1.0
  ssd_lower_bound: 1.0
  ssd_exponent: 1.0
  wandb_mode: online
  wandb_group: MainTable_CIFAR100_seed42_c10
  wandb_tags:
  - main_table
  - CIFAR100
  - class
  - SSD
  - seed42
  - c10
  baseline_name: SSD
  dataset: cifar100
  dataset_name: CIFAR100
  scenario: class
  config_name: cifar100_ssd_class
  config_path: config/main_table_cifar100_seed42/cifar100_ssd_class.yaml
  learning_rate: 0.0001
  data_dir: ./dataset/data_folder/cifar100
