seed: 42
dataset: tiny_imagenet
data_dir: ./dataset/data_folder/tiny_imagenet/tiny-imagenet-200
model_name: module_small_patch16_224
moe_layers: FFFFFFFFFFSS
num_experts: 8
gate_k: 2
expert_depth: 2
expert_hidden_ratio: 2
unlearn_algo: sg_unlearn
unlearn_setting: class
forget_classes:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
epochs: 20
batch_size: 64
lr: 0.0001
weight_decay: 0.0
fa_threshold: 0.1
alpha: 0.1
pretrained_model_path: runs/_base_models/tiny_imagenet_M8_k2_seed42/checkpoints/learn_best.pt
output_dir: runs/main_table_tiny_imagenet_seed42_c20/sg_unlearning_tiny_imagenet_class/checkpoints
study_name: SG-Unlearning__TinyImageNet__class__sg_unlearning_tiny_imagenet_class__seed42_c20
wandb_group: MainTable_TinyImageNet_seed42_c20
wandb_tags:
- main_table
- TinyImageNet
- class
- SG-Unlearning
- seed42
- c20
baseline_name: SG-Unlearning
scenario: class
config_name: sg_unlearning_tiny_imagenet_class
config_path: config/main_table_tiny_imagenet_seed42/sg_unlearning_tiny_imagenet_class.yaml
learning_rate: 0.0001
sg_use_matched_unseen: true
wandb_mode: online
