seed: 42
dataset: tiny_imagenet
data_dir: ./dataset/data_folder/tiny_imagenet/tiny-imagenet-200
model_name: spm_resnet18
pretrained_model_path: checkpoint/config/main_table_tiny_imagenet_seed42/tiny_imagenet_spm/tiny_imagenet_spm.pt
num_experts: 4
unlearn_setting: class
forget_classes:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
unlearn_algo: spm
support_size: 2048
study_name: SPM__TinyImageNet__class__tiny_imagenet_spm_unlearn_class__seed42_c20
epochs: 1
batch_size: 64
lr: 0.001
fa_threshold: 0.8
wandb_mode: online
wandb_group: MainTable_TinyImageNet_seed42_c20
wandb_tags:
- main_table
- TinyImageNet
- class
- SPM
- seed42
- c20
baseline_name: SPM
scenario: class
config_name: tiny_imagenet_spm_unlearn_class
config_path: config/main_table_tiny_imagenet_seed42/tiny_imagenet_spm_unlearn_class.yaml
learning_rate: 0.001
dataset_name: TinyImageNet
