seed: 42
dataset: pacs
data_dir: ./dataset/data_folder/pacs
model_name: module_small_patch16_224
moe_layers: FFFFFFFFFFSS
num_experts: 8
gate_k: 2
expert_depth: 2
expert_hidden_ratio: 2
unlearn_algo: l1_sparse
unlearn_setting: domain
forget_domains:
- 3
epochs: 20
batch_size: 128
lr: 0.0001
weight_decay: 0.0
fa_threshold: 0.1
alpha: 0.1
pretrained_model_path: runs/_base_models/aaedd1da4d/checkpoints/learn_best.pt
output_dir: runs/l1_stepstop/pacs_domain/checkpoints
study_name: l1-sparse_stepstop__pacs_domain
wandb_group: L1_stepstop
wandb_tags:
- l1_sparse
- ascent
- experts_only
- step_early_stop
- pacs_domain
baseline_name: l1-sparse
scenario: domain
learning_rate: 0.0001
l1_mode: ascent
baseline_update_scope: experts
eval_every_steps: 5
